import type { MasterConfig } from '../master-types';

interface CarrierAlias extends Record<string, unknown> {
  id: number;
  aliasName: string;
  carrierCode: string;
  active: boolean;
  note: string | null;
}

export const carrierAliasConfig: MasterConfig<CarrierAlias> = {
  name: 'carrierAlias',
  title: '🔀 配送便種マッピング',
  icon: '🔀',
  endpoint: '/api/master/carrier-aliases',
  primaryKey: 'id',
  searchPlaceholder: '🔍 便種名／運送会社コードで検索',
  hint: '基幹CSVの「配送便種」文字列を運送会社コードへ対応付けます。未登録の便種は既定（YMT-N）にフォールバックします。',
  filterField: 'active',
  filterPlaceholder: '─ 状態 ─',
  filterOptions: [
    { value: 'true', label: '有効のみ' },
    { value: 'false', label: '無効のみ' },
  ],
  columns: [
    { key: 'aliasName', label: '便種名（基幹CSV）' },
    { key: 'carrierCode', label: '運送会社コード', mono: true, width: 130 },
    {
      key: 'active',
      label: '有効',
      align: 'center',
      width: 56,
      render: (r) => (r.active ? '✓' : '○'),
    },
    { key: 'note', label: '備考', truncate: true },
  ],
  formFields: [
    {
      name: 'id',
      label: 'ID',
      type: 'number',
      autoGeneratedOnAdd: true,
      readonlyOnEdit: true,
      helpText: '自動採番',
    },
    {
      name: 'aliasName',
      label: '便種名（基幹CSV）',
      type: 'text',
      required: true,
      placeholder: '例: ヤマト運輸（クール便）',
      helpText: '基幹 CSV の「配送便種」列の値そのまま（重複不可）',
    },
    {
      name: 'carrierCode',
      label: '運送会社',
      type: 'select',
      required: true,
      optionsEndpoint: '/api/master/carriers',
      optionsValueField: 'code',
      optionsLabelField: 'name',
      helpText: '運送会社マスタから選択',
    },
    { name: 'active', label: '有効', type: 'boolean' },
    { name: 'note', label: '備考', type: 'textarea' },
  ],
  initialValues: { active: true },
};
