import type { MasterConfig } from '../master-types';

interface ContactSubOption extends Record<string, unknown> {
  id: number;
  category: string;
  label: string;
  sortOrder: number;
  active: boolean;
}

const CATEGORY_OPTIONS = [
  { value: 'noshi', label: '🎁 のし' },
  { value: 'product', label: '📦 商品' },
  { value: 'input', label: '📋 伝票' },
  { value: 'web', label: '🌐 WEB' },
];

const CATEGORY_LABEL: Record<string, string> = {
  noshi: '🎁 のし',
  product: '📦 商品',
  input: '📋 伝票',
  web: '🌐 WEB',
};

export const contactSubOptionConfig: MasterConfig<ContactSubOption> = {
  name: 'contactSubOption',
  title: '📢 本部連絡 サブ選択肢',
  icon: '📢',
  endpoint: '/api/master/contact-sub-options',
  primaryKey: 'id',
  searchPlaceholder: '🔍 ボタン文言で検索',
  hint: 'タブレット／ハンディの「本部連絡」で、分類（のし／商品／伝票／WEB）ごとに表示するボタン文言を管理します。タップするとこの文言が補足テキストへ挿入され、本部へはテキストで送信されます。',
  filterField: 'category',
  filterPlaceholder: '─ 分類 ─',
  filterOptions: [
    { value: 'noshi', label: '🎁 のし' },
    { value: 'product', label: '📦 商品' },
    { value: 'input', label: '📋 伝票' },
    { value: 'web', label: '🌐 WEB' },
  ],
  columns: [
    {
      key: 'category',
      label: '分類',
      width: 110,
      render: (r) => CATEGORY_LABEL[r.category] ?? r.category,
    },
    { key: 'label', label: 'ボタン文言' },
    { key: 'sortOrder', label: '表示順', align: 'center', width: 72 },
    {
      key: 'active',
      label: '有効',
      align: 'center',
      width: 56,
      render: (r) => (r.active ? '✓' : '○'),
    },
  ],
  formFields: [
    { name: 'id', label: 'ID', type: 'number', autoGeneratedOnAdd: true, readonlyOnEdit: true, helpText: '自動採番' },
    {
      name: 'category',
      label: '分類',
      type: 'select',
      required: true,
      options: CATEGORY_OPTIONS,
      helpText: '本部連絡モーダルのどの分類に表示するか',
    },
    {
      name: 'label',
      label: 'ボタン文言',
      type: 'text',
      required: true,
      placeholder: '例: 再印刷',
      helpText: 'タップで補足テキストへ挿入される文言（同じ分類内で重複不可）',
    },
    {
      name: 'sortOrder',
      label: '表示順',
      type: 'number',
      min: 0,
      step: 1,
      helpText: '小さいほど先頭に表示',
    },
    { name: 'active', label: '有効', type: 'boolean' },
  ],
  initialValues: { active: true, sortOrder: 0 },
};
