import type { MasterConfig } from '../master-types';

interface NoshiExclusion extends Record<string, unknown> {
  id: number;
  matchText: string;
  active: boolean;
  note: string | null;
}

export const noshiExclusionConfig: MasterConfig<NoshiExclusion> = {
  name: 'noshiExclusion',
  title: '🚫 のし確認 除外マスタ',
  icon: '🚫',
  endpoint: '/api/master/noshi-exclusions',
  primaryKey: 'id',
  searchPlaceholder: '🔍 除外テキストで検索',
  hint: '熨斗名称がここに登録したテキストと完全一致する伝票は、検品時の「のし☑確認」をスルーします。',
  filterField: 'active',
  filterPlaceholder: '─ 状態 ─',
  filterOptions: [
    { value: 'true', label: '有効のみ' },
    { value: 'false', label: '無効のみ' },
  ],
  columns: [
    { key: 'matchText', label: '除外テキスト（完全一致）' },
    {
      key: 'active',
      label: '有効',
      align: 'center',
      width: 56,
      render: (r) => (r.active ? '✓' : '○'),
    },
    { key: 'note', label: '備考', truncate: true },
  ],
  formFields: [
    { name: 'id', label: 'ID', type: 'number', autoGeneratedOnAdd: true, readonlyOnEdit: true, helpText: '自動採番' },
    {
      name: 'matchText',
      label: '除外テキスト',
      type: 'text',
      required: true,
      placeholder: '例: 無し',
      helpText: '熨斗名称 と完全一致で判定（重複不可）',
    },
    { name: 'active', label: '有効', type: 'boolean' },
    { name: 'note', label: '備考', type: 'textarea' },
  ],
  initialValues: { active: true },
};
