import type { MasterConfig } from '../master-types';

interface QrForceKeyword extends Record<string, unknown> {
  id: number;
  matchText: string;
  active: boolean;
  note: string | null;
}

export const qrForceKeywordConfig: MasterConfig<QrForceKeyword> = {
  name: 'qrForceKeyword',
  title: '🖨 QR印刷 強制マスタ',
  icon: '🖨',
  endpoint: '/api/master/qr-force-keywords',
  primaryKey: 'id',
  searchPlaceholder: '🔍 強制キーワードで検索',
  hint: '取込時、QR印刷フラグが OFF でも 熨斗名称／熨斗氏名 がここに登録したテキストと完全一致する場合は QR印刷フラグを ON にして取り込みます（例: 特殊包装）。',
  filterField: 'active',
  filterPlaceholder: '─ 状態 ─',
  filterOptions: [
    { value: 'true', label: '有効のみ' },
    { value: 'false', label: '無効のみ' },
  ],
  columns: [
    { key: 'matchText', label: '強制キーワード（完全一致）' },
    {
      key: 'active',
      label: '有効',
      align: 'center',
      width: 56,
      render: (r) => (r.active ? '✓' : '○'),
    },
    { key: 'note', label: '備考', truncate: true },
  ],
  formFields: [
    { name: 'id', label: 'ID', type: 'number', autoGeneratedOnAdd: true, readonlyOnEdit: true, helpText: '自動採番' },
    {
      name: 'matchText',
      label: '強制キーワード',
      type: 'text',
      required: true,
      placeholder: '例: 特殊包装',
      helpText: '熨斗名称／熨斗氏名 と完全一致で判定（重複不可）。取込時に QR を ON 化',
    },
    { name: 'active', label: '有効', type: 'boolean' },
    { name: 'note', label: '備考', type: 'textarea' },
  ],
  initialValues: { active: true },
};
