import type { MasterConfig } from '../master-types';
import type { ReactNode } from 'react';

/** 名前（太字大きめ）+ カナ（小・ミュート）を 2 段表示するセル */
function renderNameKanaCell(r: Record<string, unknown>): ReactNode {
  const name = String(r.name ?? '');
  const kana = r.kana ? String(r.kana) : '';
  const empCode = r.empCode ? String(r.empCode) : '';
  return (
    <div className="leading-tight">
      <div className="font-bold text-ink-strong text-sm truncate">
        {name || '—'}
      </div>
      <div className="text-3xs text-ink-muted truncate">
        {kana || '—'}
        {empCode && (
          <span className="ml-2 font-mono text-ink-subtle">No.{empCode}</span>
        )}
      </div>
    </div>
  );
}

interface Staff extends Record<string, unknown> {
  code: string;
  empCode: string;
  name: string;
  kana: string | null;
  role: string;
  department: string | null;
  employmentTypeCode: string | null;
  groupId: string | null;
  defaultShiftPattern: string | null;
  tel: string | null;
  joined: string | null;
  assignable: boolean;
  active: boolean;
  skillCoefficient: number;
  note: string | null;
  // Sprint Y-8: PC ログイン設定（User テーブルとの紐付け）
  loginEmail: string | null;
  pcLoginEnabled: boolean;
  loginPassword?: string; // フォーム入力用（API レスポンスには含めない）
}

// Sprint Y-7+: 部署マスタを使う形に変更（DEPARTMENT_PRESETS は廃止）
// 担当者編集モーダルが /api/master/departments から動的取得します。

export const staffConfig: MasterConfig<Staff> = {
  name: 'staff',
  title: '👤 担当者マスタ',
  icon: '👤',
  endpoint: '/api/master/staff',
  primaryKey: 'code',
  searchPlaceholder: '🔍 コード／氏名／カナ／社員番号／部署で検索',
  hint: '退職者は active=false で論理削除（実削除は履歴があるため不可）',
  filterField: 'active',
  filterPlaceholder: '─ 状態 ─',
  filterOptions: [
    { value: 'true', label: '在籍のみ' },
    { value: 'false', label: '退職のみ' },
  ],
  // Sprint Y-5: 一覧表示を再構成
  //   - コードは hidden（フォーム編集時のみ表示）
  //   - 氏名+カナ を 2 段組セルに集約
  //   - 雇用区分カラムは撤廃 → 部署 を表示
  columns: [
    {
      key: 'active',
      label: '状態',
      align: 'center',
      width: 56,
      render: (r) => (r.active ? '✓' : '✗'),
    },
    // コードは折り畳み（hidden）— 内部識別子なので一覧では非表示
    { key: 'code', label: 'コード', mono: true, width: 80, hidden: true },
    {
      key: 'name',
      label: '氏名 / カナ',
      width: 220,
      truncate: true,
      render: (r) => renderNameKanaCell(r as Record<string, unknown>),
    },
    {
      key: 'role',
      label: 'ロール',
      width: 90,
      render: (r) =>
        r.role === 'admin'
          ? '管理者'
          : r.role === 'manager'
            ? '責任者'
            : r.role === 'lead'
              ? 'リーダー'
              : r.role === 'parttime'
                ? 'アルバイト'
                : 'スタッフ',
    },
    { key: 'groupId', label: 'グループ', width: 90 },
    // 旧「雇用区分」を「部署」に置換
    { key: 'department', label: '部署', width: 100 },
    { key: 'defaultShiftPattern', label: '既定シフト', width: 90, mono: true },
    {
      key: 'skillCoefficient',
      label: 'スキル',
      align: 'right',
      width: 70,
      mono: true,
      render: (r) => Number(r.skillCoefficient).toFixed(2),
    },
    // Sprint Y-8: PC ログイン可否
    {
      key: 'pcLoginEnabled',
      label: 'PCログイン',
      align: 'center',
      width: 90,
      render: (r) =>
        r.pcLoginEnabled ? (
          <span
            className="text-3xs px-1.5 py-0.5 rounded bg-emerald-900 text-emerald-100 font-bold"
            title={r.loginEmail ? `${r.loginEmail}` : ''}
          >
            ✓ 可
          </span>
        ) : (
          <span className="text-3xs text-ink-muted">—</span>
        ),
    },
  ],
  // Sprint Y-5: フォームから「電話番号 / 入社日 / 雇用区分」を撤去し「部署」を追加
  // Sprint Y-7+: 内部コードは自動採番（S + 社員番号）。新規登録時はフォーム非表示。
  formFields: [
    {
      name: 'code',
      label: 'コード',
      type: 'text',
      readonlyOnEdit: true,
      autoGeneratedOnAdd: true,
      helpText: '自動採番（S + 社員番号）。編集時は参照のみ。',
    },
    {
      name: 'empCode',
      label: '社員番号',
      type: 'text',
      required: true,
      helpText: 'モバイルログインに使用 (重複不可)。内部コードはこの値から自動採番されます。',
    },
    { name: 'name', label: '氏名', type: 'text', required: true },
    {
      name: 'kana',
      label: 'カナ',
      type: 'text',
      transform: 'kana',
      placeholder: 'ヤマダ タロウ（ひらがな入力で自動変換）',
      helpText: 'ひらがなで入力すると自動でカタカナに変換されます',
    },
    {
      name: 'role',
      label: 'ロール',
      type: 'select',
      required: true,
      options: [
        { value: 'admin', label: '管理者 (admin)' },
        { value: 'manager', label: '責任者 (manager)' },
        { value: 'lead', label: 'リーダー (lead)' },
        { value: 'staff', label: 'スタッフ (staff)' },
        { value: 'parttime', label: 'アルバイト (parttime)' },
      ],
      helpText:
        'リーダー = 検品 + CSV出力 + レポート閲覧（マスタ編集不可）。アルバイト = 検品のみ',
    },
    {
      name: 'department',
      label: '部署',
      type: 'select',
      placeholder: '部署を選択',
      // Sprint Y-7+: 部署マスタから動的取得（active のみ）。
      //   登録は 🏢 部署マスタ タブから。staff.department は varchar(30) で text を保存するため
      //   value/label とも「部署名」を使う（既存データ・一覧表示・既存ロジックとの互換性保持）。
      optionsEndpoint: '/api/master/departments',
      optionsValueField: 'name',
      optionsLabelField: 'name',
      helpText: '🏢 部署マスタで登録した部署から選択（active=true のみ表示）',
    },
    // Sprint Y-7+: FK の手入力ミスを防ぐためマスタから動的取得（空欄で未割当）
    {
      name: 'groupId',
      label: 'グループ',
      type: 'select',
      placeholder: '─ 未割当 ─',
      optionsEndpoint: '/api/master/groups',
      optionsValueField: 'id',
      optionsLabelField: 'name',
      helpText: 'グループマスタから選択（未割当でも保存可）',
    },
    {
      name: 'defaultShiftPattern',
      label: '既定シフトパターン',
      type: 'select',
      placeholder: '─ 未設定 ─',
      optionsEndpoint: '/api/master/shift-patterns',
      optionsValueField: 'code',
      optionsLabelField: 'name',
      helpText: 'シフトパターンマスタから選択（例: G7 / 公休）',
    },
    { name: 'assignable', label: '割当可', type: 'boolean', helpText: 'メンバー割当ガントの対象にする' },
    { name: 'active', label: '在籍', type: 'boolean', helpText: '退職者は OFF（モバイルログイン不可になる）' },
    {
      name: 'skillCoefficient',
      label: 'スキル係数',
      type: 'number',
      step: 0.001,
      min: 0,
      max: 9.999,
      helpText: '1.000=標準。Phase 6-9 で実績ログから自動更新',
    },
    { name: 'note', label: '備考', type: 'textarea' },
    // Sprint Y-8: PC ログイン設定（モバイル端末は社員番号のみで OK。管理 PC を使う担当者だけ設定）
    {
      name: 'pcLoginEnabled',
      label: 'PC ログイン可',
      type: 'boolean',
      helpText:
        'ON にすると下のメール / パスワードで管理 PC にログインできるようになります（モバイル端末は社員番号のみで利用可）',
    },
    {
      name: 'loginEmail',
      label: 'PC ログインメール',
      type: 'text',
      placeholder: 'taro.yamada@oenosato.local',
      helpText: '社内メール推奨。同じメールは複数人で使えません',
    },
    {
      name: 'loginPassword',
      label: 'PC ログインパスワード',
      type: 'password',
      placeholder: '新規=必須 ／ 編集時=空欄で変更スキップ',
      helpText: '8 文字以上推奨。編集時に空欄で保存すると変更されません',
    },
  ],
  initialValues: {
    role: 'staff',
    assignable: true,
    active: true,
    skillCoefficient: 1.0,
    pcLoginEnabled: false,
  },
};
