'use client';

/**
 * マスタ汎用 編集モーダル
 *
 * モック準拠（管理用PCモック_v0.22.html L5070-5081 mstEditModal）。
 *
 * - 動的フォーム（FormField[] から生成）
 * - 'add' / 'edit' モード
 * - edit 時は 🗑 削除ボタン表示
 * - cancel / 保存
 */

import { useEffect, useState } from 'react';
import type { FormField } from './master-types';

interface Props<T extends Record<string, unknown>> {
  open: boolean;
  mode: 'add' | 'edit';
  title: string;
  hint?: string;
  fields: FormField[];
  initialValues?: Partial<T>;
  onSave: (values: Record<string, unknown>) => Promise<void> | void;
  onDelete?: () => Promise<void> | void;
  onCancel: () => void;
}

export function MasterEditModal<T extends Record<string, unknown>>({
  open,
  mode,
  title,
  hint,
  fields,
  initialValues,
  onSave,
  onDelete,
  onCancel,
}: Props<T>) {
  const [values, setValues] = useState<Record<string, unknown>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Sprint Y-7+: optionsEndpoint 経由の動的選択肢
  const [dynamicOptions, setDynamicOptions] = useState<
    Record<string, { value: string; label: string }[]>
  >({});

  // optionsEndpoint を持つフィールドについて、モーダル open のたびに取得
  useEffect(() => {
    if (!open) return;
    const tasks = fields
      .filter((f) => f.type === 'select' && f.optionsEndpoint)
      .map(async (f) => {
        try {
          const r = await fetch(f.optionsEndpoint!);
          if (!r.ok)
            return {
              name: f.name,
              opts: [] as { value: string; label: string }[],
            };
          const j = await r.json();
          const items: unknown[] = j?.data?.items ?? [];
          const vk = f.optionsValueField ?? 'code';
          const lk = f.optionsLabelField ?? 'name';
          const opts = items
            .filter(
              (it) =>
                !!it &&
                typeof it === 'object' &&
                (('active' in (it as Record<string, unknown>)
                  ? (it as Record<string, unknown>).active !== false
                  : true)),
            )
            .map((it) => {
              const o = it as Record<string, unknown>;
              return {
                value: String(o[vk] ?? ''),
                label: String(o[lk] ?? o[vk] ?? ''),
              };
            })
            .filter((o) => o.value.length > 0);
          return { name: f.name, opts };
        } catch {
          return {
            name: f.name,
            opts: [] as { value: string; label: string }[],
          };
        }
      });
    Promise.all(tasks).then((entries) => {
      const map: Record<string, { value: string; label: string }[]> = {};
      for (const e of entries) map[e.name] = e.opts;
      setDynamicOptions(map);
    });
  }, [open, fields]);

  // open のたびに値を初期化
  useEffect(() => {
    if (!open) return;
    const init: Record<string, unknown> = {};
    for (const f of fields) {
      const v = initialValues?.[f.name as keyof T];
      if (v !== undefined) {
        init[f.name] = v;
      } else if (f.type === 'boolean') {
        init[f.name] = false;
      } else if (f.type === 'number') {
        init[f.name] = '';
      } else {
        init[f.name] = '';
      }
    }
    setValues(init);
    setError(null);
    setBusy(false);
  }, [open, fields, initialValues]);

  // Esc キャンセル
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !busy) onCancel();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, busy, onCancel]);

  if (!open) return null;

  function setField(name: string, v: unknown) {
    setValues((prev) => ({ ...prev, [name]: v }));
  }

  async function handleSave() {
    // 必須バリデーション
    for (const f of fields) {
      if (f.required) {
        const v = values[f.name];
        const empty =
          v === undefined ||
          v === null ||
          (typeof v === 'string' && v.trim().length === 0);
        if (empty) {
          setError(`「${f.label}」は必須項目です`);
          return;
        }
      }
    }
    setBusy(true);
    setError(null);
    try {
      // number 型は文字列から変換
      const out: Record<string, unknown> = {};
      for (const f of fields) {
        // Sprint Y-7+: 新規登録時の自動採番フィールドは送信しない（サーバが採番）
        if (mode === 'add' && f.autoGeneratedOnAdd) continue;
        const v = values[f.name];
        if (f.type === 'number') {
          if (v === '' || v === null || v === undefined) {
            out[f.name] = null;
          } else {
            out[f.name] = Number(v);
          }
        } else if (f.type === 'boolean') {
          out[f.name] = !!v;
        } else if (typeof v === 'string' && v === '') {
          // 空文字は null として送る（Zod の string().min(1).optional() で
          // "" が弾かれる問題を回避。サーバ側で nullable を許容している前提）
          out[f.name] = null;
        } else {
          out[f.name] = v ?? null;
        }
      }
      await onSave(out);
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
    }
  }

  async function handleDelete() {
    if (!onDelete) return;
    if (!confirm('このレコードを削除します。よろしいですか？')) return;
    setBusy(true);
    setError(null);
    try {
      await onDelete();
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div
      className="fixed inset-0 bg-black/65 flex items-center justify-center z-50 p-4 backdrop-blur-sm"
      onClick={(e) => {
        if (e.target === e.currentTarget && !busy) onCancel();
      }}
    >
      <div className="bg-surface-panel border-2 border-accent-amber rounded-[10px] shadow-modal max-w-xl w-full max-h-[90vh] overflow-auto">
        <div className="px-4 py-3 border-b border-surface-border">
          <h3 className="text-base font-bold text-ink-strong">
            {mode === 'add' ? '＋ ' : '✏ '}
            {title}
          </h3>
          {hint && <div className="text-3xs text-ink-muted mt-0.5">{hint}</div>}
        </div>

        <div className="p-4 space-y-2">
          {error && (
            <div className="text-2xs bg-status-error-bg text-status-error border border-status-error rounded p-2">
              {error}
            </div>
          )}

          {fields
            // Sprint Y-7+: 新規登録時に隠すフィールド（自動採番列）
            .filter((f) => !(mode === 'add' && f.autoGeneratedOnAdd))
            .map((f) => (
              <FieldRow
                key={f.name}
                field={f}
                value={values[f.name]}
                disabled={busy || (mode === 'edit' && !!f.readonlyOnEdit)}
                dynamicOptions={dynamicOptions[f.name]}
                onChange={(v) => setField(f.name, v)}
              />
            ))}
        </div>

        <div className="px-4 py-3 border-t border-surface-border flex items-center gap-2">
          {mode === 'edit' && onDelete && (
            <button
              onClick={handleDelete}
              disabled={busy}
              className="px-3 py-1.5 rounded border border-status-error/50 bg-red-950/30 text-red-200 text-xs hover:bg-red-900 disabled:opacity-50"
            >
              🗑 削除
            </button>
          )}
          <div className="flex-1" />
          <button
            onClick={onCancel}
            disabled={busy}
            className="px-3 py-1.5 rounded border border-surface-border bg-surface-base text-ink text-xs disabled:opacity-50"
          >
            キャンセル
          </button>
          <button
            onClick={handleSave}
            disabled={busy}
            className="px-4 py-1.5 rounded bg-brand-primary text-white text-xs font-bold hover:bg-blue-600 disabled:opacity-50"
          >
            {busy ? '保存中…' : '✓ 保存'}
          </button>
        </div>
      </div>
    </div>
  );
}

function FieldRow({
  field,
  value,
  disabled,
  dynamicOptions,
  onChange,
}: {
  field: FormField;
  value: unknown;
  disabled: boolean;
  dynamicOptions?: { value: string; label: string }[];
  onChange: (v: unknown) => void;
}) {
  return (
    <div className="grid grid-cols-[120px_1fr] gap-2 items-start">
      <label className="text-2xs text-ink-subtle pt-1.5">
        {field.label}
        {field.required && <span className="text-status-error ml-0.5">*</span>}
      </label>
      <div>
        {renderInput(field, value, disabled, onChange, dynamicOptions)}
        {field.helpText && (
          <div className="text-3xs text-ink-muted mt-0.5">{field.helpText}</div>
        )}
      </div>
    </div>
  );
}

function renderInput(
  field: FormField,
  value: unknown,
  disabled: boolean,
  onChange: (v: unknown) => void,
  dynamicOptions?: { value: string; label: string }[],
): React.ReactNode {
  const baseCls =
    'w-full bg-surface-base border border-surface-border rounded px-2 py-1.5 text-xs text-ink disabled:opacity-50';

  switch (field.type) {
    case 'textarea':
      return (
        <textarea
          value={String(value ?? '')}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          placeholder={field.placeholder}
          rows={3}
          className={`${baseCls} resize-none`}
        />
      );
    case 'select': {
      // Sprint Y-7+: optionsEndpoint で取得した動的選択肢があれば優先
      //   (現在値が動的取得結果に含まれない場合でも表示できるようフォールバック option を追加)
      const opts =
        dynamicOptions && dynamicOptions.length > 0
          ? dynamicOptions
          : (field.options ?? []).map((o) => ({
              value: String(o.value),
              label: o.label,
            }));
      const currentValue = String(value ?? '');
      const missingCurrent =
        currentValue.length > 0 && !opts.some((o) => o.value === currentValue);
      return (
        <select
          value={currentValue}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          className={baseCls}
        >
          <option value="">{field.placeholder ?? '─ 選択 ─'}</option>
          {missingCurrent && (
            <option value={currentValue}>{currentValue}（旧値）</option>
          )}
          {opts.map((o) => (
            <option key={o.value} value={o.value}>
              {o.label}
            </option>
          ))}
        </select>
      );
    }
    case 'boolean':
      return (
        <label className="flex items-center gap-2 cursor-pointer text-xs text-ink">
          <input
            type="checkbox"
            checked={!!value}
            onChange={(e) => onChange(e.target.checked)}
            disabled={disabled}
            className="cursor-pointer"
          />
          {field.helpText ?? '有効'}
        </label>
      );
    case 'number':
      return (
        <input
          type="number"
          value={value === null || value === undefined ? '' : String(value)}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          min={field.min}
          max={field.max}
          step={field.step}
          placeholder={field.placeholder}
          className={`${baseCls} font-mono tabular-nums`}
        />
      );
    case 'date':
      return (
        <input
          type="date"
          value={String(value ?? '')}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          className={`${baseCls} font-mono`}
        />
      );
    case 'password':
      return (
        <input
          type="password"
          value={String(value ?? '')}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          placeholder={field.placeholder}
          autoComplete="new-password"
          className={`${baseCls} font-mono tracking-wider`}
        />
      );
    default:
      return (
        <input
          type="text"
          value={String(value ?? '')}
          onChange={(e) => {
            const raw = e.target.value;
            // Sprint Y-7+: transform='kana' のフィールドは入力中にひらがな→カタカナ変換
            const converted =
              field.transform === 'kana' ? hiraganaToKatakana(raw) : raw;
            onChange(converted);
          }}
          disabled={disabled}
          placeholder={field.placeholder}
          className={baseCls}
        />
      );
  }
}

/**
 * Sprint Y-7+: ひらがな → カタカナ 変換ヘルパー
 *   - U+3041 (ぁ) 〜 U+3096 (ゖ) を +0x60 シフトで全角カタカナに
 *   - 半角文字・既にカタカナ・英数字はそのまま
 */
function hiraganaToKatakana(s: string): string {
  return s.replace(/[ぁ-ゖ]/g, (ch) =>
    String.fromCharCode(ch.charCodeAt(0) + 0x60),
  );
}
